### PR TITLE
Pure Java WinRM client

### PR DESCRIPTION
**Pull request by neykov**
Implement the WinRM protocol using JAX-WS client, removing the python dependncy.

The end result is really simple, but quite fiddly to come up with. To create the client I first needed to create a service, so now we should be able to use it for tests, or even extend it to work with generic winrm clients.

### CODE REVIEW

**Comment by neykov** [comment]
Addressed conflicts. Live tests are passing.

**Comment by neykov** [comment]
Have looked deeper in the available authentication methods. The WinRM service supports:
  * Basic (disabled by default)
  * Negotiate, which selects one of
    * Kerberos
    * NTLM
  * Certificate (disabled by default)
  * CredSSP (disabled by default) - used when scripts executed on the server need to authenticate to another server on behalf of the user

## Basic
The standard HTTP Basic auth, works out of the box

## Kerberos
Can be used only when the server is part of a domain.

## NTLM
Used for local accounts (only the Administrator user [out of the box](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384295%28v=vs.85%29.aspx)) or when accessing the server though IP (not using FQDN).

## Certificate
Similar to the SSH private key based auth, can use one of the above to configure this one, just as jclouds does.

---
Even though the [Java docs](https://docs.oracle.com/javase/7/docs/technotes/guides/net/http-auth.html) suggest that HttpUrlConnection supports all schemes from above I wasn't able to use neither NTLM nor Kerberos successfully so far. Most of the suggestions in the wild are to use one of [jCIFS](http://spnego.sourceforge.net/), [SPNEGO](https://www.google.bg/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjjk5i8mpPKAhWBfiwKHYAvAcUQFggeMAA&url=https%3A%2F%2Fjcifs.samba.org%2F&usg=AFQjCNEK4mUXa4ou_xB9EnofUuvz0Fy8gg), [Jespa](http://www.ioplex.com/jespa.html) which are either LGPL or commercially licensed.

Another option is to switch the http client to [Apache Http Components](https://hc.apache.org/httpcomponents-client-ga/ntlm.html) and see if that works better. Can be used in [combination with jCIFS](https://gist.github.com/moberwasserlechner/4690931) as well

**Comment by aledsage** [comment]
Excellent - thanks @neykov merging now.

**Comment by neykov** [comment]
Changes needed to support  Negotiage(SPNEGO)+NTLM with Apache HttpComponents Client (note that this overrides Negotiate+Kerberos):

ApacheSpnegoScheme.java:
```java
import org.apache.http.Header;
import org.apache.http.HttpRequest;
import org.apache.http.auth.AuthenticationException;
import org.apache.http.auth.Credentials;
import org.apache.http.client.config.AuthSchemes;
import org.apache.http.impl.auth.NTLMScheme;
import org.apache.http.message.BasicHeader;

public class ApacheSpnegoScheme extends NTLMScheme{

    @Override
    public String getSchemeName() {
        return AuthSchemes.SPNEGO;
    }

    @Override
    public Header authenticate(Credentials credentials, HttpRequest request)
            throws AuthenticationException {
        Header hdr = super.authenticate(credentials, request);
        return new BasicHeader(hdr.getName(), hdr.getValue().replace("NTLM", getSchemeName()));
    }

}
```

SpNegoNTLMSchemeFactory.java
```java

import org.apache.http.auth.AuthScheme;
import org.apache.http.impl.auth.NTLMSchemeFactory;
import org.apache.http.params.HttpParams;
import org.apache.http.protocol.HttpContext;

public class SpNegoNTLMSchemeFactory extends NTLMSchemeFactory {

    @Override
    public AuthScheme create(HttpContext context) {
        return new ApacheSpnegoScheme();
    }

  
}
```

configure the client:
```java
        CredentialsProvider credsProvider = new BasicCredentialsProvider();
        credsProvider.setCredentials(
                new AuthScope("windows.host.amazonaws.com", 5985),
                new NTCredentials("Administrator", "XXXXXX", "YYYY", "WIN-ZZZZZ"));

        Registry<AuthSchemeProvider> authSchemeRegistry = RegistryBuilder.<AuthSchemeProvider>create()
                .register(AuthSchemes.BASIC, new BasicSchemeFactory())
                // Uncomment to support Negotiate(SPNEGO)+Kerberos, only one of the next two items allowed
                // .register(AuthSchemes.SPNEGO, new SPNegoSchemeFactory())
                .register(AuthSchemes.SPNEGO, new SpNegoNTLMSchemeFactory())
                .register(AuthSchemes.KERBEROS, new KerberosSchemeFactory())
                .build();

        CloseableHttpClient httpclient = HttpClients.custom()
                .setDefaultCredentialsProvider(credsProvider)
                .setDefaultAuthSchemeRegistry(authSchemeRegistry)
                .build();


```

**Pull request merged**
