### PR TITLE
Missing build method authenticationScheme needed for tests

### PR DESCRIPTION
**Pull request by bostko**

### CODE REVIEW

**Comment by bostko** [comment]
@Graeme-Miller could you review this? Thanks.

**Comment by neykov** [comment]
@bostko There's already a method to set the scheme but it's called `setAuthenticationScheme`. No idea why, better keep the convention. +1 for the change, but can you mark the existing one as `@Deprecated`.

**Comment by bostko** [comment]
@neykov sorry, addressed your comment.

**Comment by neykov** [comment]
thanks @bostko, LGTM

**Comment by GQsj** [comment]
Is this branch not be added to the master? In my pull code, there is no method called authenticationScheme, and the AbstractWinRmToolLiveTest.java report the error message.

**Pull request merged**
