### PR TITLE
Support for specification of HostnameVerifier in WinRmTool and WinRmC…

### PR DESCRIPTION
**Pull request by semancik**
…lient.

### CODE REVIEW

**Comment by neykov** [comment]
Thanks for the changes @semancik. Happy to merge them.
Just would like to confirm that you are aware of the project licensing and are happy with it. Current project license is Apache 2.0. We noticed a leftover (duplicate) license in the repo from a previous implementation based on pywinrm. That's  fixed in https://github.com/cloudsoft/winrm4j/pull/38.

**Comment by semancik** [comment]
Yes. I'm more than happy with Apache License 2.0. And thank you for maintaining this project.

**Comment by neykov** [comment]
@semancik there's a new 0.4.0 release of winrm4j including the change now.

**Comment by semancik** [comment]
Thank you. That's very helpful.

**Pull request merged**
